name: Python tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        sudo apt-get install sagemath
        sage -pip install pycryptodome 
        sage -pip install pytest
    - name: Test with pytest
      run: |
        PYTHONPATH="$DOT_SAGE/local/lib/python3.10/site-packages" $DOT_SAGE/local/bin/pytest
